insert into free_board (title, content, writer, created_at, updated_at) values ('제목1', '1번글입니다','황윤호', now(), now());
insert into free_board (title, content, writer, created_at, updated_at) values ('제목2', '2번글입니다','황윤호', now(), now());
insert into free_board (title, content, writer, created_at, updated_at) values ('제목3', '3번글입니다','황윤호', now(), now());
insert into free_board (title, content, writer, created_at, updated_at) values ('제목4', '4번글입니다','황윤호', now(), now());
insert into free_board (title, content, writer, created_at, updated_at) values ('제목5', '5번글입니다','황윤호', now(), now());
insert into free_board (title, content, writer, created_at, updated_at) values ('제목6', '6번글입니다','황윤호', now(), now());
insert into free_board (title, content, writer, created_at, updated_at) values ('제목7', '7번글입니다','황윤호', now(), now());
insert into free_board (title, content, writer, created_at, updated_at) values ('제목8', '8번글입니다','황윤호', now(), now());
insert into free_board (title, content, writer, created_at, updated_at) values ('제목9', '9번글입니다','황윤호', now(), now());
insert into free_board (title, content, writer, created_at, updated_at) values ('제목10', '10번글입니다', '황윤호', now(), now());
insert into free_board (title, content, writer, created_at, updated_at) values ('제목11', '11번글입니다', '황윤호', now(), now());
insert into free_board (title, content, writer, created_at, updated_at) values ('제목12', '12번글입니다', '황윤호', now(), now());
insert into free_board (title, content, writer, created_at, updated_at) values ('제목13', '13번글입니다', '황윤호', now(), now());
insert into free_board (title, content, writer, created_at, updated_at) values ('제목14', '14번글입니다', '황윤호', now(), now());
insert into free_board (title, content, writer, created_at, updated_at) values ('제목15', '15번글입니다', '황윤호', now(), now());
insert into free_board (title, content, writer, created_at, updated_at) values ('제목16', '16번글입니다', '황윤호', now(), now());
insert into free_board (title, content, writer, created_at, updated_at) values ('제목17', '17번글입니다', '황윤호', now(), now());
insert into free_board (title, content, writer, created_at, updated_at) values ('제목18', '18번글입니다', '황윤호', now(), now());
insert into free_board (title, content, writer, created_at, updated_at) values ('제목19', '19번글입니다', '황윤호', now(), now());
insert into free_board (title, content, writer, created_at, updated_at) values ('제목20', '20번글입니다', '황윤호', now(), now());
insert into free_board (title, content, writer, created_at, updated_at) values ('제목21', '21번글입니다', '황윤호', now(), now());
insert into free_board (title, content, writer, created_at, updated_at) values ('제목22', '22번글입니다', '황윤호', now(), now());